defaults:
- _self_
- index: FlatL2   
- connector: simple_df_connector
- override hydra/hydra_logging: disabled    # disaple output dir  
- override hydra/job_logging: disabled     # disaple output dir  
  
# disaple output dir  
hydra:  
  output_subdir: null  
  run:  
    dir: .

memory_footprint_training: 10_000_000  # how many bytes reserved for index training
memory_footprint_populating: 0.5 
batch_size: 1  
index_dir: "${hydra:runtime.cwd}/index/${now:%Y-%m-%d}"

